# leaf-2 data file
ip_routing: true

lldp:
  run: true

domain_list:
  - lab.net
local_users:
  ansible:
    privilege: 15
    sha512_password: "$6$VsWOuPuN97JAhwSy$uY.ZftNmdrvNmUnZmVkXWNzSREpWV8IHIyepvYxh1cN43zY.r9Yzndz8/aZ5m0Zf4vSk5BNKeKNlnlBjZgOsX0"

# migrating to eos cli gen
router_bgp:
  as: 65012
  router_id: 1.1.1.4
  bgp_defaults:
    - ""
  neighbors:
    10.0.2.1:
      remote_as: 65000
      description: "spine-1"
    10.2.0.1:
      remote_as: 65000
      description: "spine-2"
  address_family_ipv4:
    networks:
      192.0.2.4/32:
router_ospf:
  process_ids:
    100:
      passive_interface_default: false
      router_id: 1.1.1.4
      log_adjacency_changes_detail: true

ethernet_interfaces:
  Ethernet1:
    ip_address: 10.0.100.2/24
    type: routed
    shutdown: false
    description: leaf-1
    ospf_network_point_to_point: true
    ospf_area: 0
  Ethernet2:
    ip_address: 10.0.2.2/24
    type: routed
    shutdown: false
    description: spine-1
    ospf_network_point_to_point: true
    ospf_area: 0
  Ethernet3:
    ip_address: 10.2.0.2/24
    type: routed
    shutdown: false
    description: spine-2
    ospf_network_point_to_point: true
    ospf_area: 0

loopback_interfaces:
  loopback1:
    ip_address: 172.16.1.4/32
    description: Lo1
    ospf_network_point_to_point: false
    ospf_area: 0
  loopback2:
    ip_address: 192.0.2.4/32
    description: Lo2
