# leaf-1 data file
lldp:
  run: true

domain_list:
  - lab.net
local_users:
  ansible:
    privilege: 15
    sha512_password: "$6$VsWOuPuN97JAhwSy$uY.ZftNmdrvNmUnZmVkXWNzSREpWV8IHIyepvYxh1cN43zY.r9Yzndz8/aZ5m0Zf4vSk5BNKeKNlnlBjZgOsX0"

# migrating to eos cli gen
router_bgp:
  as: 65011
  router_id: 1.1.1.3
  bgp_defaults:
    - ""
  neighbors:
    10.0.1.1:
      remote_as: 65000
      description: "spine-1"
    10.1.0.1:
      remote_as: 65000
      description: "spine-2"

router_ospf:
  process_ids:
    100:
      passive_interface_default: false
      router_id: 1.1.1.3
      log_adjacency_changes_detail: true

ethernet_interfaces:
  Ethernet1:
    ip_address: 10.0.100.1/24
    type: routed
    shutdown: false
    description: leaf-2
    ospf_network_point_to_point: true
    ospf_area: 0
  Ethernet2:
    ip_address: 10.0.1.2/24
    type: routed
    shutdown: false
    description: spine-1
    ospf_network_point_to_point: true
    ospf_area: 0
  Ethernet3:
    ip_address: 10.1.0.2/24
    type: routed
    shutdown: false
    description: spine-2
    ospf_network_point_to_point: true
    ospf_area: 0

loopback_interfaces:
  loopback1:
    ip_address: 172.16.1.3/32
    description: Lo1
    ospf_network_point_to_point: false
    ospf_area: 0
